compatibility_flags = []
compatibility_date = "2026-04-18"
name = "fitness"

[build]
command = "npm run build"
directory = "dist"

[[routes]]
route = "fitness.sbnone.dpdns.org/*"  # 如果你用自定义域名
zone_name = "sbnone.dpdns.org"
